services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - aidr-network

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    networks:
      - aidr-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: aidr
      POSTGRES_PASSWORD: aidrpass
      POSTGRES_DB: aidr_db
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aidr-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - aidr-network

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    container_name: ingestor
    depends_on:
      - kafka
      - postgres
      - redis
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aidr_db
      SPRING_DATASOURCE_USERNAME: aidr
      SPRING_DATASOURCE_PASSWORD: aidrpass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - aidr-network

volumes:
  pgdata:

networks:
  aidr-network:
    driver: bridge